[package]
name = "rdom"
version = "0.1.0"
authors = ["Philip Peterson <philip.c.peterson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
thiserror = "1"
