name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: '00 01 * * *'
jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
#         - stable
#         - beta
        - nightly-pinned
        include:
#         - build: stable
#           os: ubuntu-latest
#           rust: stable
#         - build: beta
#           os: ubuntu-latest
#           rust: beta
        - build: nightly-pinned
          os: ubuntu-latest
          rust: nightly-2021-03-23  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Build rdom
      run: cargo build --verbose --all
